"""create table matches and relationships

Revision ID: 8e820a011f0d
Revises: e8867eaa37bf
Create Date: 2026-02-22 18:00:36.004789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e820a011f0d'
down_revision = 'e8867eaa37bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monitor_id', 'property_id', name='uq_monitor_property_match')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('idx_match_notified_matched_at', ['notified', 'matched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_matched_at'), ['matched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_property_id'))
        batch_op.drop_index(batch_op.f('ix_matches_monitor_id'))
        batch_op.drop_index(batch_op.f('ix_matches_matched_at'))
        batch_op.drop_index('idx_match_notified_matched_at')

    op.drop_table('matches')
    # ### end Alembic commands ###
