"""create monitors table and relationship with users

Revision ID: a41903f9b349
Revises: 1c5352e719f0
Create Date: 2026-02-22 16:49:04.557303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41903f9b349'
down_revision = '1c5352e719f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'STUDIO', name='property_type_enum'), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_bedrooms', sa.Integer(), nullable=False),
    sa.Column('min_area', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_price > 0', name='check_max_price_positive'),
    sa.CheckConstraint('min_area >= 0', name='check_min_area_non_negative'),
    sa.CheckConstraint('min_bedrooms >= 0', name='check_min_bedrooms_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.create_index('idx_monitor_location_type', ['state', 'city', 'neighborhood', 'property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitors_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitors_user_id'))
        batch_op.drop_index('idx_monitor_location_type')

    op.drop_table('monitors')
    # ### end Alembic commands ###
