"""create tables properties and property_prices

Revision ID: e8867eaa37bf
Revises: a41903f9b349
Create Date: 2026-02-22 17:33:11.019244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8867eaa37bf'
down_revision = 'a41903f9b349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'HOUSE', 'STUDIO', name='property_type_enum'), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('idx_property_location_type', ['state', 'city', 'neighborhood', 'property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_source'), ['source'], unique=False)

    op.create_table('property_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price > 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_prices', schema=None) as batch_op:
        batch_op.create_index('idx_property_price_property_created', ['property_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_prices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_prices_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_prices_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_prices_created_at'))
        batch_op.drop_index('idx_property_price_property_created')

    op.drop_table('property_prices')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_source'))
        batch_op.drop_index(batch_op.f('ix_properties_created_at'))
        batch_op.drop_index('idx_property_location_type')

    op.drop_table('properties')
    # ### end Alembic commands ###
